server:
  interface: 127.0.0.1@5353
  interface: ::1@5353
  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow
  do-udp: yes
  do-tcp: yes
  cache-max-negative-ttl: 60

forward-zone:
  name: "."
  forward-addr: 1.1.1.1@53
  forward-addr: 8.8.8.8@53
  forward-tcp-upstream: yes
