import test from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import router from '../routes/api.js';
import { Placement } from '../models/Placement.js';
import { Learner } from '../models/Learner.js';
import { IndustryPartner } from '../models/IndustryPartner.js';
import { PlacementRequest } from '../models/PlacementRequest.js';
import { PlacementCoordinator } from '../models/PlacementOperation.js';

test('standalone placement lifecycle, permissions, capacity, duplicates and interrupted activation recovery', { skip: process.env.PLACEMENT_MONGO_INTEGRATION !== '1' }, async t => {
  await mongoose.connect(`mongodb://127.0.0.1:27030/placement_workflow_qa_${Date.now()}`, { autoIndex: false, serverSelectionTimeoutMS: 3000 });
  try {
    assert.equal(await Placement.countDocuments(), 0, 'Use a fresh disposable QA database');
    await Placement.collection.createIndex({ learner: 1 }, { name: 'one_active_placement_per_learner', unique: true, partialFilterExpression: { status: 'Active' } });
    const id = () => new mongoose.Types.ObjectId();
    const user = { _id: id(), role: 'Admin', institution: 'QA', name: 'QA Admin' };
    const learners = [id(), id(), id(), id()];
    await Learner.collection.insertMany(learners.map(_id => ({ _id, institution: 'QA', phone: '0000000000', program: 'IT', year: 'Year 1', academicStatus: 'Active', status: 'Pending' })));
    await mongoose.connection.db.collection('institutions').insertOne({ name: 'QA', region: 'Greater Accra', calendarType: 'Single Track' });
    const partnerId = id();
    await IndustryPartner.collection.insertOne({ _id: partnerId, name: 'QA partner', sector: 'IT', region: 'Greater Accra', status: 'Active', approvalStatus: 'Approved', totalSlots: 1, usedSlots: 99 });
    const now = new Date(), year = now.getFullYear() - (now.getMonth() < 7 ? 1 : 0);
    const academicYear = `${year}/${year + 1}`;
    const startDate = now.toISOString().slice(0, 10), endDate = new Date(now.getTime() + 86400000 * 30).toISOString().slice(0, 10);
    await mongoose.connection.db.collection('academiccalendars').insertOne({ eventType: 'WEL Window', isActive: true, academicYear, institutionCalendarType: 'Single Track', targetYearGroup: 'Year 1', semester: 'Semester 1', startDate: new Date(now.getTime() - 86400000), endDate: new Date(now.getTime() + 86400000 * 60) });
    const call = async (path, method, body = {}, params = {}, actor = user) => {
      const handler = router.stack.find(layer => layer.route?.path === path && layer.route.methods[method]).route.stack.at(-1).handle;
      const res = { code: 200, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; } };
      await handler({ body, params, user: actor, query: {} }, res);
      return res;
    };
    const input = { learners: [String(learners[0])], partner: String(partnerId), coordinates: { lat: 0, lng: 0 }, startDate, endDate, academicYear, placementRegion: 'Greater Accra', delegate: id(), owner: id() };
    const first = await call('/placements', 'post', input);
    assert.equal(first.code, 201, JSON.stringify(first.body));
    const placementId = String(first.body[0]._id);
    assert.equal(first.body[0].delegate, undefined);
    assert.equal(first.body[0].owner, undefined);
    assert.equal((await IndustryPartner.findById(partnerId)).usedSlots, 1);
    const retry = await call('/placements', 'post', input);
    assert.equal(retry.code, 200);
    assert.equal(String(retry.body[0]._id), placementId);
    assert.equal(await Placement.countDocuments(), 1);
    const full = await call('/placements', 'post', { ...input, learners: [String(learners[1])] });
    assert.equal(full.code, 409);
    await assert.rejects(Placement.collection.insertOne({ learner: learners[0], status: 'Active' }), error => error.code === 11000);
    assert.equal((await call('/placements/:id', 'delete', {}, { id: placementId })).code, 409);
    const terminated = await call('/placements/:id', 'put', { status: 'Terminated', closedBy: id() }, { id: placementId });
    assert.equal(terminated.code, 200, JSON.stringify(terminated.body));
    assert.equal(String(terminated.body.closedBy), String(user._id));
    assert.equal((await Learner.findById(learners[0])).status, 'Pending');
    assert.equal((await Learner.findById(learners[0])).placement, undefined);
    assert.equal((await IndustryPartner.findById(partnerId)).usedSlots, 0);
    assert.equal((await call('/placements/:id', 'put', { status: 'Active' }, { id: placementId })).code, 200);
    assert.equal(String((await Learner.findById(learners[0])).placement), placementId);
    assert.equal((await call('/placements/:id', 'put', { status: 'Completed' }, { id: placementId }, { ...user, role: 'Staff' })).code, 403);
    assert.equal((await call('/placements/:id', 'put', { status: 'Completed' }, { id: placementId })).code, 200);
    await mongoose.connection.db.collection('attendancelogs').insertOne({ placement: new mongoose.Types.ObjectId(placementId), learner: learners[0] });
    assert.equal((await call('/placements/:id', 'delete', {}, { id: placementId })).code, 200);
    assert.ok((await Placement.findById(placementId)).archivedAt);
    assert.equal(await mongoose.connection.db.collection('attendancelogs').countDocuments(), 1);
    assert.equal((await call('/placements/:id', 'put', { status: 'Active' }, { id: placementId })).code, 409);
    const submitted = await call('/placement-requests', 'post', { ...input, learners: [String(learners[1])], requestedSlots: -99, program: 'IT' }, {}, { ...user, role: 'Staff' });
    assert.equal(submitted.code, 201, JSON.stringify(submitted.body));
    assert.equal(submitted.body.status, 'Submitted');
    assert.equal(submitted.body.requestedSlots, 1);
    assert.equal(await Placement.countDocuments({ status: 'Active' }), 0);
    const failOnce = t.mock.method(Learner, 'updateOne', async () => { throw new Error('Simulated learner write outage'); });
    const activation = await call('/placement-requests/:id/convert', 'post', { coordinates: input.coordinates }, { id: String(submitted.body._id) });
    assert.equal(activation.code, 500);
    assert.equal(await Placement.countDocuments({ learner: learners[1], status: 'Active' }), 1);
    assert.ok((await PlacementCoordinator.findById('global')).pending);
    failOnce.mock.restore();
    const recovered = await call('/placement-requests/:id/convert', 'post', { coordinates: input.coordinates }, { id: String(submitted.body._id) });
    assert.equal(recovered.code, 200, JSON.stringify(recovered.body));
    assert.equal(recovered.body.status, 'Converted');
    assert.equal(await Placement.countDocuments({ learner: learners[1], status: 'Active' }), 1);
    assert.equal((await IndustryPartner.findById(partnerId)).usedSlots, 1);
    assert.equal((await Learner.findById(learners[1])).status, 'Placed');
    assert.equal((await PlacementCoordinator.findById('global')).pending, undefined);
    assert.equal((await PlacementRequest.findById(submitted.body._id)).convertedPlacementIds.length, 1);
    const rejectedPartner = await call('/placements', 'post', { ...input, learners: [String(learners[2])], partner: String(id()) });
    assert.equal(rejectedPartner.code, 400);
    const reversed = await call('/placements', 'post', { ...input, learners: [String(learners[2])], endDate: '2000-01-01' });
    assert.equal(reversed.code, 400);
    const foreign = await call('/placements/:id', 'put', { status: 'Completed' }, { id: placementId }, { ...user, institution: 'Other' });
    assert.equal(foreign.code, 404);
    const outsideWindow = await call('/placements', 'post', { ...input, learners: [String(learners[2])], endDate: new Date(now.getTime() + 86400000 * 365).toISOString().slice(0, 10) });
    assert.equal(outsideWindow.code, 400);
    assert.match(outsideWindow.body.message, /WEL window/);
    const concurrentPartner = id();
    await IndustryPartner.collection.insertOne({ _id: concurrentPartner, name: 'Concurrent QA', sector: 'IT', region: 'Greater Accra', status: 'Active', approvalStatus: 'Approved', totalSlots: 1, usedSlots: 0 });
    const contenders = [learners[2], learners[3]].map(learner => ({ ...input, learners: [String(learner)], partner: String(concurrentPartner) }));
    const concurrent = await Promise.all(contenders.map(body => call('/placements', 'post', body)));
    assert.equal(concurrent.filter(result => result.code === 201).length, 1, JSON.stringify(concurrent.map(result => ({ code: result.code, body: result.body }))));
    assert.equal(concurrent.filter(result => result.code === 409).length, 1);
    const loser = concurrent.findIndex(result => result.code === 409);
    const retryLoser = await call('/placements', 'post', contenders[loser]);
    assert.equal(retryLoser.code, 409);
    assert.equal(await Placement.countDocuments({ partner: concurrentPartner, status: 'Active' }), 1);
    assert.equal((await IndustryPartner.findById(concurrentPartner)).usedSlots, 1);
  } finally { await mongoose.disconnect(); }
});
