import test from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { createWorkplaceSearchHandler } from '../utils/workplaceSearch.js';
import { TownLookupCache, TownLookupGate } from '../models/TownLookup.js';
import { IndustryPartner } from '../models/IndustryPartner.js';
import { locationCheck, normalizeCoordinates } from '../utils/workplaceCoordinates.js';
import { normalizePartnerChanges } from '../utils/partnerChanges.js';
import router from '../routes/api.js';
import { Learner } from '../models/Learner.js';
import { Placement } from '../models/Placement.js';
import { PlacementRequest } from '../models/PlacementRequest.js';
const uri = process.env.GTVET_HEALTH_TEST_URI;
const res = () => ({ statusCode: 200, set() { return this; }, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; return this; } });
test('shared Mongo search gate caches lookups and selected locations drive monitoring verification', { skip: !uri }, async () => {
  const target = new URL(uri); assert.equal(target.hostname, '127.0.0.1'); assert.equal(target.pathname, '/gtvet_system_health_test');
  // Avoid building unrelated modules' indexes during this isolated cold-database test.
  await mongoose.connect(uri, { serverSelectionTimeoutMS: 2000, autoIndex: false, autoCreate: false });
  try {
    await mongoose.connection.db.dropDatabase();
    await Promise.all([TownLookupCache.createCollection(), TownLookupGate.createCollection()]);
    await TownLookupCache.createIndexes();
    let calls = 0;
    const fetchImpl = async () => {
      calls++;
      await new Promise(resolve => setTimeout(resolve, 100));
      return { ok: true, json: async () => [{ display_name: 'Kumasi, Ashanti, Ghana', lat: '6.68', lon: '-1.62', osm_type: 'node', osm_id: 123, addresstype: 'city', address: { country_code: 'gh' } }] };
    };
    const first = res(), second = res();
    await Promise.all([createWorkplaceSearchHandler({ env: {}, fetchImpl })({ query: { q: 'Kumasi' } }, first), createWorkplaceSearchHandler({ env: {}, fetchImpl })({ query: { q: 'Adenta' } }, second)]);
    assert.equal(calls, 1); assert.deepEqual([first.statusCode, second.statusCode].sort(), [200, 429]);
    const success = first.statusCode === 200 ? first : second;
    const cached = res();
    await createWorkplaceSearchHandler({ env: {}, fetchImpl })({ query: { q: first.statusCode === 200 ? 'KUMASI' : 'ADENTA' } }, cached);
    assert.equal(calls, 1); assert.deepEqual(cached.body, success.body);
    const blocked = res(); await createWorkplaceSearchHandler({ env: {}, fetchImpl })({ query: { q: 'Tamale' } }, blocked);
    assert.equal(blocked.statusCode, 429); assert.equal(calls, 1);
    assert.ok((await TownLookupGate.findById('nominatim')).nextAt > new Date());
    const indexes = await TownLookupCache.collection.indexes(); assert.ok(indexes.some(index => index.expireAfterSeconds === 0));
    const approximateLocation = success.body.results[0];
    const registered = res();
    const actor = { _id: new mongoose.Types.ObjectId(), role: 'SuperAdmin', name: 'QA actor' };
    const create = router.stack.find(layer => layer.route?.path === '/industry-partners' && layer.route.methods.post).route.stack.at(-1).handle;
    await create({ user: actor, body: { name: 'Town lookup QA partner', sector: 'Automotive', region: 'Ashanti', town: 'Kumasi', approximateLocation, coordinates: { lat: approximateLocation.lat, lng: approximateLocation.lng, precision: 'Town', townName: approximateLocation.name } } }, registered);
    assert.equal(registered.statusCode, 201);
    const partner = registered.body;
    const saved = await IndustryPartner.findById(partner._id).lean();
    assert.equal(saved.approximateLocation.precision, 'Town'); assert.equal(saved.locationVerificationStatus, 'TownSelected'); assert.equal(saved.coordinates.precision, 'Town');
    assert.equal(locationCheck({ lat: 6.70, lng: -1.62 }, saved.coordinates).locationVerified, 'Verified');
    const learnerId = new mongoose.Types.ObjectId();
    await Learner.collection.insertOne({ _id: learnerId, firstName: 'QA', lastName: 'Learner', institution: 'QA', indexNumber: 'qa-1' });
    const request = await PlacementRequest.create({ institution: 'QA', program: 'Automotive', requestedSlots: 1, learners: [learnerId], submittedBy: actor._id, partner: partner._id, coordinates: normalizeCoordinates(saved.coordinates) });
    const placement = await Placement.create({ learner: learnerId, institution: 'QA', partner: partner._id, companyName: partner.name, sector: 'Automotive', location: 'Kumasi', coordinates: normalizeCoordinates(request.coordinates), locationVerificationStatus: 'TownSelected' });
    const logVisit = router.stack.find(layer => layer.route?.path === '/monitoring-visits' && layer.route.methods.post).route.stack.at(-1).handle;
    const staff = { ...actor, role: 'Staff', institution: 'QA' };
    const visitBody = { learner: String(learnerId), placement: String(placement._id), visitDate: new Date(), visitType: 'Routine', attendanceStatus: 'Present', performanceRating: 3 };
    const inside = res(); await logVisit({ user: staff, body: { ...visitBody, submittedLocation: { lat: 6.70, lng: -1.62 }, verificationRadiusMetres: 999999, verificationLocationType: 'Actual' } }, inside);
    assert.equal(inside.statusCode, 201, JSON.stringify(inside.body)); assert.equal(inside.body.locationVerified, 'Verified'); assert.equal(inside.body.verificationLocationType, 'Town'); assert.equal(inside.body.verificationRadiusMetres, 5000);
    const unexplained = res(); await logVisit({ user: staff, body: { ...visitBody, submittedLocation: { lat: 6.76, lng: -1.62 } } }, unexplained);
    assert.equal(unexplained.statusCode, 400);
    const outside = res(); await logVisit({ user: staff, body: { ...visitBody, submittedLocation: { lat: 6.76, lng: -1.62 }, gpsExceptionReason: 'Follow-up meeting outside the selected town area.' } }, outside);
    assert.equal(outside.statusCode, 201); assert.equal(outside.body.gpsReviewStatus, 'PendingReview');
    await Placement.updateOne({ _id: placement._id }, { $set: { coordinates: { lat: 6.68, lng: -1.62, precision: 'Actual' } } });
    const actual = res(); await logVisit({ user: staff, body: { ...visitBody, submittedLocation: { lat: 6.70, lng: -1.62 }, gpsExceptionReason: 'Meeting was arranged away from the workplace.' } }, actual);
    assert.equal(actual.statusCode, 201); assert.equal(actual.body.locationVerified, 'Unverified'); assert.equal(actual.body.verificationRadiusMetres, 500);
    assert.equal(inside.body.referenceCoordinates.precision, 'Town');
    assert.deepEqual(normalizePartnerChanges({ approximateLocation }), { approximateLocation });
    await IndustryPartner.updateOne({ _id: partner._id }, { $set: { coordinates: { lat: 5.6, lng: -0.2 } } }, { runValidators: true });
    assert.equal((await IndustryPartner.findById(partner._id)).coordinates.lat, 5.6);
    const update = router.stack.find(layer => layer.route?.path === '/industry-partners/:id' && layer.route.methods.put).route.stack.at(-1).handle;
    const edited = res(); await update({ user: actor, params: { id: String(partner._id) }, body: { town: 'Adenta' } }, edited);
    assert.equal(edited.statusCode, 200); assert.equal(edited.body.approximateLocation, null); assert.equal(edited.body.coordinates.lat, 5.6);
    const cleared = res(); await update({ user: actor, params: { id: String(partner._id) }, body: { coordinates: null } }, cleared);
    assert.equal(cleared.statusCode, 200); assert.equal(cleared.body.coordinates, undefined); assert.equal(cleared.body.locationVerificationStatus, 'PendingGPS');
    await TownLookupCache.updateMany({}, { $set: { expiresAt: new Date(0) } });
    await TownLookupGate.updateOne({ _id: 'nominatim' }, { $set: { nextAt: new Date(0) } });
    const expired = res(); await createWorkplaceSearchHandler({ env: {}, fetchImpl })({ query: { q: 'Kumasi' } }, expired); assert.equal(calls, 2);
  } finally { await mongoose.connection.db.dropDatabase(); await mongoose.disconnect(); }
});
